# !/bin/bash

tap "homebrew/services"
tap "homebrew/bundle"
tap "buo/cask-upgrade"
tap "koekeishiya/formulae"
tap "jesseduffield/lazygit"

# cli tools
brew 'archey4'
brew 'asdf'
brew 'atuin'
brew 'bat'
brew 'btop'
brew 'coreutils'
brew 'cppman'
brew 'diff-so-fancy'
brew 'eza'
brew 'fd'
brew 'fzf'
brew 'gawk'
brew 'gh'
brew 'git-delta'
brew 'glow'
brew 'gpg'
brew 'hey'
brew 'htop'
brew 'hub'
brew 'jq'
brew 'kubectl'
brew 'lazygit'
brew 'mongocli'
brew 'mosh'
brew 'most'
brew 'neovim'
brew 'osx-cpu-temp'
brew 'powerlevel10k'
brew 'ripgrep'
brew 'rsync'
brew 'stow'
brew 'the_silver_searcher'
brew 'tldr'
brew 'tmux'
brew 'tmuxinator'
brew 'tree'
brew 'vivid'
brew 'wget'
brew 'zoxide'
brew 'zsh'
brew 'zzz'
brew 'koekeishiya/formulae/yabai'
brew 'koekeishiya/formulae/skhd'

# dev macos apps
cask 'alacritty'
cask 'karabiner-elements'
cask 'git-credential-manager'
cask 'miniconda'
cask 'ngrok'
cask 'pgadmin4'
cask 'postman'
cask 'qbittorrent'
cask 'raycast'
cask 'tailscale'
cask 'vagrant'
cask 'wireshark'

# non-dev macos apps
cask 'anki'
cask 'brave-browser'
cask 'bitwarden'
cask 'figma'
cask 'discord'
cask 'google-chrome'
cask 'the-unarchiver'
cask 'vlc'
cask 'zoom'
cask 'purevpn'

# programming languages & package managers
brew 'lua'
brew 'luarocks'
brew 'pnpm'
brew 'yarn'
brew 'rustup'
brew 'python'

# nerd fonts
cask 'font-fira-code-nerd-font'
cask 'font-go-mono-nerd-font'
cask 'font-hack-nerd-font'
cask 'font-hasklug-nerd-font'
cask 'font-jetbrains-mono-nerd-font'
cask 'font-meslo-lg-nerd-font'
cask 'font-monoid-nerd-font'
cask 'font-mononoki-nerd-font'
cask 'font-sauce-code-pro-nerd-font'
cask 'font-space-mono-nerd-font'
