require "config.globals"
require "config.mapping"
require "config.lazy-nvim"
require "config.theme"
require "config.autocmds"
require "config.options"
require "config.filetypes"
require "config.debug"
