#!/bin/bash

# Adapting this sketchybar config from @hbthen3rd:
# https://github.com/hbthen3rd/dotfiles/blob/master/.config/sketchybar

source "$HOME/.config/sketchybar/colors.sh"
source "$HOME/.config/sketchybar/icons.sh"

PLUGIN_DIR="$HOME/.config/sketchybar/plugins"

FONT="Hasklug Nerd Font"

##### Bar Appearance #####
# Configuring the general appearance of the bar, these are only some of the
# options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar color=$BAR_COLOR \
                 position=bottom  \
                 height=26        \
                 margin=0         \
                 y_offset=0       \
                 padding_left=8   \
                 padding_right=8

##### Changing Defaults #####
# We now change some default values that are applied to all further items
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

sketchybar --default padding_left=8                                    \
                     padding_right=8                                   \
                                                                       \
                     background.height=26                              \
                     background.corner_radius=12                       \
                                                                       \
                     icon.color="$MAGENTA"                          \
                     icon.highlight_color="$BACKGROUND"            \
                     icon.padding_left=6                               \
                     icon.padding_right=2                              \
                     icon.font="Hasklug Nerd Font:Regular:14.0"  \
                                                                       \
                     label.color=$MAGENTA                         \
                     label.highlight_color=$BACKGROUND           \
                     label.padding_left=2                              \
                     label.padding_right=6                             \
                     label.font="Hasklug Nerd Font:Regular:14.0"

##### Adding Menu #####

# sketchybar --add item command.logo left                                                                     \
#            --set      command.logo background.color=$GREEN                                            \
#                                    background.border_width=0                                                \
#                                    background.corner_radius=12                                               \
#                                    background.height=26                                                     \
#                                    icon=$ICON_CMD                                                           \
#                                    icon.highlight=on                                                        \
#                                    icon.padding_left=6                                                      \
#                                    icon.padding_right=6                                                     \
#                                    label.drawing=off                                                        \
#                                    click_script="sketchybar -m --set \$NAME popup.drawing=toggle"           \
#                                    popup.height=32                                                          \
#                                    popup.background.color=$BACKGROUND                                 \
#                                    popup.background.border_width=0                                          \
#                                    popup.background.corner_radius=6                                       \
#                                    popup.background.border_color=$GREEN                               \
#                                                                                                             \
#            --add item command.preferences popup.command.logo                                                \
#            --set      command.preferences icon=$ICON_COG                                                    \
#                                           icon.color=$GREEN                                           \
#                                           icon.padding_left=4                                               \
#                                           icon.padding_right=2                                              \
#                                           label="Settings"                                                  \
#                                           label.color=$GREEN                                          \
#                                           label.padding_left=2                                              \
#                                           label.padding_right=4                                             \
#                                           click_script="open -a 'System Preferences';                    
#                                                         sketchybar -m --set command.logo popup.drawing=off" \
#            --add item command.activity popup.command.logo                                                   \
#            --set      command.activity icon=$ICON_CHART                                                     \
#                                        icon.color=$GREEN                                              \
#                                        icon.padding_left=4                                                  \
#                                        icon.padding_right=2                                                 \
#                                        label="Task Manager"                                                 \
#                                        label.color=$GREEN                                             \
#                                        label.padding_left=2                                                 \
#                                        label.padding_right=4                                                \
#                                        click_script="open -a 'Activity Monitor';                       
#                                                      sketchybar -m --set command.logo popup.drawing=off"    \
#            --add item command.lock popup.command.logo                                                       \
#            --set      command.lock icon=$ICON_LOCK                                                          \
#                                    icon.color=$GREEN                                                  \
#                                    icon.padding_left=4                                                      \
#                                    icon.padding_right=2                                                     \
#                                    label="Sleep"                                                            \
#                                    label.color=$GREEN                                                 \
#                                    label.padding_left=2                                                     \
#                                    label.padding_right=4                                                    \
#                                    click_script="pmset displaysleepnow;                           
#                                                  sketchybar -m --set command.logo popup.drawing=off"
#
# sketchybar --add bracket cmd command.logo                         \
#            --set         cmd background.color=$BACKGROUND   \
#                              background.border_color=$GREEN
#
# sketchybar --add item seperator.l1 left                   \
#            --set      seperator.l1 padding_left=4         \
#                                    padding_right=4        \
#                                    background.drawing=off \
#                                    icon.drawing=off       \
#                                    label.drawing=off
#
##### Adding Mission Control Space Indicators #####
# Now we add some mission control spaces:
# https://felixkratz.github.io/SketchyBar/config/components#space----associate-mission-control-spaces-with-an-item
# to indicate active and available mission control spaces

# sketchybar --add event window_change
#
# COLORS_SPACE=($YELLOW $CYAN $MAGENTA $WHITE $BLUE $RED $GREEN)
# LENGTH=${#ICONS_SPACE[@]}
#
# for i in "${!ICONS_SPACE[@]}"
# do
#   sid=$(($i+1))
#   PAD_LEFT=2
#   PAD_RIGHT=2
#   if [[ $i == 0 ]]; then
#     PAD_LEFT=8
#   elif [[ $i == $(($LENGTH-1)) ]]; then
#     PAD_RIGHT=8
#   fi
#   sketchybar --add space space.$sid left                                       \
#              --set       space.$sid script="$PLUGIN_DIR/app_space.sh"          \
#                                     associated_space=$sid                      \
#                                     padding_left=$PAD_LEFT                     \
#                                     padding_right=$PAD_RIGHT                   \
#                                     background.color=${COLORS_SPACE[i]}        \
#                                     background.border_width=0                  \
#                                     background.corner_radius=6                 \
#                                     background.height=24                       \
#                                     icon=${ICONS_SPACE[i]}                     \
#                                     icon.color=${COLORS_SPACE[i]}              \
#                                     label="_"                                  \
#                                     label.color=${COLORS_SPACE[i]}             \
#              --subscribe space.$sid front_app_switched window_change
# done
#
# sketchybar --add bracket spaces '/space\..*/'                      \
#            --set         spaces background.color=$BACKGROUND
#
# sketchybar --add item seperator.l2 left                   \
#            --set      seperator.l2 padding_left=4         \
#                                    padding_right=4        \
#                                    background.drawing=off \
#                                    icon.drawing=off       \
#                                    label.drawing=off
#
#
SPACE_ICONS=("1" "2" "3" "4" "5" "6" "7" "8" "9" "10" "11" "12" "13" "14" "15")

# Destroy space on right click, focus space on left click.
# New space by left clicking separator (>)

sid=0
spaces=()
for i in "${!SPACE_ICONS[@]}"
do
  sid=$(($i+1))

  space=(
    associated_space=$sid
    icon="${SPACE_ICONS[i]}"
    icon.padding_left=10
    icon.padding_right=10
    padding_left=2
    padding_right=2
    label.padding_right=20
    icon.highlight_color=$PITCH
    label.color=$MAGENTA
    label.highlight_color=$PITCH
    label.font="sketchybar-app-font:Regular:14.0"
    label.y_offset=-1
    background.color=$BACKGROUND
    background.border_color=$BACKGROUND
    background.drawing=off
    label.drawing=off
    script="$PLUGIN_DIR/space.sh"
  )

  sketchybar --add space space.$sid left    \
             --set space.$sid "${space[@]}" \
             --subscribe space.$sid mouse.clicked
done

spaces_bracket=(
  background.color=$BACKGROUND
  background.border_color=$BACKGROUND
)

separator=(
  icon=􀆊
  icon.font="$FONT:Heavy:14.0"
  padding_left=10
  padding_right=8
  label.drawing=off
  associated_display=active
  click_script='yabai -m space --create && sketchybar --trigger space_change'
  icon.color=$WHITE
)

sketchybar --add bracket spaces_bracket '/space\..*/'  \
           --set spaces_bracket "${spaces_bracket[@]}" \
                                                       \
           --add item separator left                   \
           --set separator "${separator[@]}"

## Yabai.sh Item ##
yabai=(
  icon.width=0
  label.width=0
  script="$PLUGIN_DIR/yabai.sh"
  icon.font="$FONT:Bold:14.0"
  associated_display=active
)

sketchybar --add event window_focus            \
           --add event windows_on_spaces       \
           --add item yabai left               \
           --set yabai "${yabai[@]}"           \
           --subscribe yabai window_focus      \
                             space_change      \
                             windows_on_spaces \
                             mouse.scrolled.global \
                             mouse.clicked

## Front_app.sh Item ##
FRONT_APP_SCRIPT='[ "$SENDER" = "front_app_switched" ] && sketchybar --set $NAME label="$INFO"'

front_app=(
  icon.drawing=off
  label.font="$FONT:Regular:14.0"
  associated_display=active
  script="$FRONT_APP_SCRIPT"
)

sketchybar --add item front_app left         \
           --set front_app "${front_app[@]}" \
           --subscribe front_app front_app_switched


##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other items respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events

sketchybar --add item time right                        \
           --set      time script="$PLUGIN_DIR/time.sh" \
                           update_freq=5                \
                           padding_left=2               \
                           padding_right=0              \
                           background.color=$RED  \
                           background.border_width=0    \
                           background.corner_radius=12   \
                           background.height=24         \
                           icon=$ICON_CLOCK             \
                           icon.highlight=on            \
                           label.highlight=on           \
           --add item date right                        \
           --set      date script="$PLUGIN_DIR/date.sh" \
                           update_freq=60               \
                           padding_left=8               \
                           padding_right=2              \
                           background.border_width=0    \
                           background.height=24         \
                           icon=$ICON_CALENDAR          \
                           icon.color=$RED        \
                           label.color=$RED

sketchybar --add bracket clock time date                          \
           --set         clock background.color=$BACKGROUND \
                               # background.border_color=$RED


sketchybar --add item seperator.r1 right                  \
           --set      seperator.r1 padding_left=4         \
                                   padding_right=4        \
                                   background.drawing=off \
                                   icon.drawing=off       \
                                   label.drawing=off

sketchybar --add item  ip_address right                              \
           --set       ip_address script="$PLUGIN_DIR/ip_address.sh" \
                                  update_freq=30                     \
                                  padding_left=2                     \
                                  padding_right=0                    \
                                  background.border_width=0          \
                                  background.corner_radius=12         \
                                  background.height=26               \
                                  icon.highlight=on                  \
                                  label.highlight=on                 \
           --subscribe ip_address wifi_change                        \
                                                                     \
           --add item  volume right                                  \
           --set       volume script="$PLUGIN_DIR/volume.sh"         \
                              padding_left=2                         \
                              padding_right=2                        \
                              background.border_width=0              \
                              background.height=24                   \
           --subscribe volume volume_change                          \
                                                                     \
           --add item  battery right                                 \
           --set       battery script="$PLUGIN_DIR/battery.sh"       \
                               update_freq=120                       \
                               padding_left=8                        \
                               padding_right=2                       \
                               background.border_width=0             \
                               background.height=24                  \
           --subscribe battery system_woke power_source_change

sketchybar --add bracket status ip_address volume battery           \
           --set         status background.color=$BACKGROUND  \
                                # background.border_color=$BLUE

sketchybar --add item seperator.r2 right                  \
           --set      seperator.r2 padding_left=4         \
                                   padding_right=4        \
                                   background.drawing=off \
                                   icon.drawing=off       \
                                   label.drawing=off

sketchybar --add item swap right                        \
           --set      swap script="$PLUGIN_DIR/swap.sh" \
                           update_freq=60               \
                           padding_left=2               \
                           padding_right=8              \
                           background.border_width=0    \
                           background.height=24         \
                           icon=$ICON_SWAP              \
                           icon.color=$CYAN       \
                           label.color=$CYAN      \
                                                        \
           --add item ram right                         \
           --set      ram script="$PLUGIN_DIR/ram.sh"   \
                          update_freq=60                \
                          padding_left=2                \
                          padding_right=2               \
                          background.border_width=0     \
                          background.height=26          \
                          icon=$ICON_RAM                \
                          icon.color=$GREEN       \
                          label.color=$GREEN      \
                                                        \
           --add item disk right                        \
           --set      disk script="$PLUGIN_DIR/disk.sh" \
                           update_freq=60               \
                           padding_left=2               \
                           padding_right=2              \
                           background.border_width=0    \
                           background.height=26         \
                           icon=$ICON_DISK              \
                           icon.color=$YELLOW     \
                           label.color=$YELLOW    \
                                                        \
           --add item cpu right                         \
           --set      cpu script="$PLUGIN_DIR/cpu.sh"   \
                          update_freq=60                \
                          padding_left=8                \
                          padding_right=2               \
                          background.border_width=0     \
                          background.height=24          \
                          icon=$ICON_CPU                \
                          icon.color=$RED         \
                          label.color=$RED

sketchybar --add bracket activity swap ram disk cpu                      \
           --set         activity background.color=$BACKGROUND     \
                                  background.border_color=$MAGENTA

##### Finalizing Setup #####
# The below command is only needed at the end of the initial configuration to
# force all scripts to run the first time, it should never be run in an item script.

# sketchybar --updatesource "$HOME/.config/sketchybar/icons.sh"
sketchybar --update
echo "sketchybar configuation loaded.."
